// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtgz_OBuUSjieV2-sLfm-5UfyR0odawzU',
    appId: '1:12067668867:android:ad5c1a93fa747f90d02cb6',
    messagingSenderId: '12067668867',
    projectId: 'codeforces-visualizer',
    storageBucket: 'codeforces-visualizer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT_8A_ho2BoCTf_xGx2FAMssUHwnugnK0',
    appId: '1:12067668867:ios:4dfe266888e6851cd02cb6',
    messagingSenderId: '12067668867',
    projectId: 'codeforces-visualizer',
    storageBucket: 'codeforces-visualizer.appspot.com',
    androidClientId: '12067668867-asjcsacllq7adnqnm1o1flo4o9kfd4l7.apps.googleusercontent.com',
    iosClientId: '12067668867-0c5hjum5mdkst4iiea2pf0vrafvs8io8.apps.googleusercontent.com',
    iosBundleId: 'com.example.codeforcesVisualizer',
  );
}
